// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4d2b3e93DecodeGithubComTarasusrusUrlShortenerInternalAppModels(in *jlexer.Lexer, out *ShortenResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.ShortURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4d2b3e93EncodeGithubComTarasusrusUrlShortenerInternalAppModels(out *jwriter.Writer, in ShortenResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.ShortURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4d2b3e93EncodeGithubComTarasusrusUrlShortenerInternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4d2b3e93EncodeGithubComTarasusrusUrlShortenerInternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4d2b3e93DecodeGithubComTarasusrusUrlShortenerInternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4d2b3e93DecodeGithubComTarasusrusUrlShortenerInternalAppModels(l, v)
}
func easyjson4d2b3e93DecodeGithubComTarasusrusUrlShortenerInternalAppModels1(in *jlexer.Lexer, out *ShortenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4d2b3e93EncodeGithubComTarasusrusUrlShortenerInternalAppModels1(out *jwriter.Writer, in ShortenRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4d2b3e93EncodeGithubComTarasusrusUrlShortenerInternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4d2b3e93EncodeGithubComTarasusrusUrlShortenerInternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4d2b3e93DecodeGithubComTarasusrusUrlShortenerInternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4d2b3e93DecodeGithubComTarasusrusUrlShortenerInternalAppModels1(l, v)
}
